- name: Facts Demo
  hosts: iosxe1*
  gather_facts: false
  vars:
    network_os:
      - ios
      - eos
      - junos

  tasks:
    - name: Collect Custom Facts Manually
      cisco.ios.ios_facts:
        gather_network_resources: all
        gather_subset: all
    
    - name: Change GE1 Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "GE1 Hello 22"
      when:
        - somevar is not defined
        - ansible_facts['net_system'] in network_os
        - ansible_facts['net_memfree_mb'] > 2250 or ansible_facts['net_iostype'] == 'IOS-XE'
        - ansible_facts['net_model'] == 'C8000V'
        # List of conditions is 'and' operator
      # when: ansible_facts['net_memfree_mb'] > 2250 and ansible_facts['net_model'] == 'C8000V'

    # - name: Save Facts in File
    #   delegate_to: workstation.lab.example.com
    #   ansible.builtin.copy:
    #     content: |
    #       Net API         = {{ ansible_facts['net_api'] }}
    #       Hostname        = {{ ansible_facts['net_hostname'] }}
    #       IOS Type        = {{ ansible_facts['net_iostype'] }}
    #       Model           = {{ ansible_facts['net_model'] }}
    #       Python Version  = {{ ansible_facts['net_python_version'] }}
    #       Serial Number   = {{ ansible_facts['net_serialnum'] }}
    #       Net System      = {{ ansible_facts['net_system'] }}
    #       Net Version     = {{ ansible_facts['net_version'] }}
    #       Free Memory     = {{ ansible_facts['net_filesystems_info']['bootflash:']['spacefree_kb'] }} KB
    #       Total Memory     = {{ ansible_facts['net_filesystems_info']['bootflash:']['spacetotal_kb'] }} KB
    #       acls            = {{ ansible_facts['network_resources']['acls'] }}
    #       HSRP Interfaces = {{ ansible_facts['network_resources']['hsrp_interfaces'] }}
    #     dest: /tmp/{{ inventory_hostname }}.txt

