- name: Test IP reachability
  hosts: iosxe1.lab.example.com
  gather_facts: false
  tasks:
    - name: Check IP reachability
      ansible.builtin.include_role:
        name: network.healthchecks.interfaces
      vars:
        interfaces_health_check:
          name: health_check
          vars:
            checks:
              - name: min_operational_state_up
                min_count: 1

    - name: Display reachability results
      ansible.builtin.debug:
        var: health_checks
